export const range = document.querySelector('#range');
export const form = document.querySelector('.ad-form');
export const roomsField = form.querySelector('[name="rooms"]');
export const capacityField = form.querySelector('[name="capacity"]');
export const priceField = document.querySelector('#price');
export const formInputs = document.querySelectorAll('.ad-form__watch-focus');
export const timeFieldset = document.querySelector('#time-fieldset');
export const timeFields = timeFieldset.querySelectorAll('select');
export const typeField = document.querySelector('#type');
